set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES x86_64)
# Cross-compiling on arm64 runner: skip cmake try_run() tests (like aom pie_check)
set(VCPKG_CMAKE_CONFIGURE_OPTIONS
    -DCMAKE_SYSTEM_PROCESSOR=x86_64
    -DCMAKE_CROSSCOMPILING=ON
)
